### ISSUE TITLE
Where can I get the clip encoders for JK_workflow_txt2img_img2img_SDXL?

### ISSUE THREAD

**Issue by PudyJapan** [jakechai/ComfyUI-JakeUpgrade#103]
Hi,

I am checking JK_workflow_txt2img_img2img_SDXL and I can see it uses dual clip loader that says:

        t5xxl\clip_g
        t5xxl\clip_l

I didn't find those in the huggingface page for sdxl.
Are those the ones with SD3?

I can see fp16 and fp8 versions of t5xxl text encoders on SD3 page and non-t5xxl clip_l and clip_g.

Thank you for advance.

**Comment by jakechai** [comment]
They are the same clip g and clip l for SD3.

**Comment by PudyJapan** [comment]
> They are the same clip g and clip l for SD3.

Thank you very much for getting back to me. For the sake of confirmation and for anyone else looking for it, those two, right?

https://huggingface.co/stabilityai/stable-diffusion-3-medium/blob/main/text_encoders/clip_g.safetensors
https://huggingface.co/stabilityai/stable-diffusion-3-medium/blob/main/text_encoders/clip_l.safetensors

**Comment by jakechai** [comment]
That's right!

**Comment by PudyJapan** [comment]
@jakechai Thanks. I'm getting this error after using the SD3 medium clip files with the workflow "JK_workflow_txt2img_img2img_SDXL "

**Comment by PudyJapan** [comment]
I'm so sorry, I just forgot to input prompt. My bad.
