### ISSUE TITLE
TypeError: theirNode.widgets is undefined

### ISSUE THREAD

**Issue by Eggwardhan** [jakechai/ComfyUI-JakeUpgrade#110]
Loading aborted due to error reloading workflow data

TypeError: theirNode.widgets is undefined

adaptWidgetsToConnection@http://127.0.0.1:8188/extensions/comfyui-tooling-nodes/external_tooling_nodes.js:152:29
setupParameterNode/nodeType.prototype.onAfterGraphConfigured@http://127.0.0.1:8188/extensions/comfyui-tooling-nodes/external_tooling_nodes.js:173:33
#addAfterConfigureHandler/app2.graph.onConfigure@http://127.0.0.1:8188/assets/index-BHayQCxv.js:78088:15
configure@http://127.0.0.1:8188/assets/index-BHayQCxv.js:69322:10
#addConfigureHandler/LGraph.prototype.configure@http://127.0.0.1:8188/assets/index-BHayQCxv.js:78040:26
init/LGraph.prototype.configure@http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/reroutePrimitive.js:14:29
loadGraphData@http://127.0.0.1:8188/assets/index-BHayQCxv.js:78562:18

This may be due to the following script:
/extensions/comfyui-tooling-nodes/external_tooling_nodes.js

when I try to load JK：：Image Gen SDXL，it raise this error

**Comment by jakechai** [comment]
If you are referring to this error, ignore it. It's due to the tooling custom nodes.
![tooling](https://github.com/user-attachments/assets/f8fcff93-8d4d-469f-b3b5-8efc559ba993)
