### ISSUE TITLE
Server Execution Error: ClipVision model not found.''

### ISSUE THREAD

**Issue by one903045** [jakechai/ComfyUI-JakeUpgrade#111]
Hey,can it work with the newest vision krita-ai-diffusion and Krita 5.26?
when I generate， it report errors''Server Execution Erro: ClipVision model not found.'' or generate  the same picture as ai-diffusion'generate。
![屏幕截图_7-12-2024_63635_127 0 0 1](https://github.com/user-attachments/assets/4281e5da-6418-4fdf-84ee-18404b082c15)

**Comment by jakechai** [comment]
I will look into it.

**Comment by jakechai** [comment]
It looks fine to me except for the order of the parameters, which I'm still working on.
Did you install the IP Adapter model which is needed for this workflow?
![clip vision](https://github.com/user-attachments/assets/ae2eb97a-f638-4b29-9aa3-1b5f2ff44bad)

**Comment by one903045** [comment]
thank you，I install the newest IP Adapter,and Change the Krita language，it work successful now。
