### ISSUE TITLE
JK_workflow_txt2img_img2img_SDXL.json has a loop?

### ISSUE THREAD

**Issue by lunias** [jakechai/ComfyUI-JakeUpgrade#115]
There appears to be a loop upon running this workflow?

![image](https://github.com/user-attachments/assets/52cff6c4-1550-44f2-a4ba-30208bbc2fc8)

Perhaps I am doing something wrong... I also can't identify the loop

**Comment by jakechai** [comment]
The pre-process switches might cause loops such as: Process Base -> Process Detailer -> Process Upscale -> Process Detailer.
But I'm not sure what this loop warning is referring to. You might need to show your workflow.

**Comment by lunias** [comment]
![image](https://github.com/user-attachments/assets/31edb29d-fe55-4c7a-8abc-c4cb1eb56550)
I simply imported the workflow, installed the missing nodes and clicked queue. I haven't made any modifications

**Comment by jakechai** [comment]
I found out that the first Enable Process Base is off. This one needs to be always on. I'll do some tests.

**Comment by jakechai** [comment]
The warning didn't show up if I turned off the Enable Process Base. ComfyUI version issue?

**Comment by lunias** [comment]
ComfyUI v0.3.7
ComfyUI_frontend v1.4.13

Enable process base is on by default, but I turned it off to see if it would have an impact. I also watched your youtube video and still couldn't figure out where I was going wrong. II did try out the handfix module workflow on its own and that worked.

I messed w/ the workflow trying to get it to work, but this is happening for me even with a fresh import from the json file...

**Comment by jakechai** [comment]
That confuses me either. Updating ComfyUI to the latest works fine for me. I'll try v0.3.7.

**Comment by jakechai** [comment]
v0.3.7 still works, whether the Enable Process Base is on or off. That might be something I don't know...
![works](https://github.com/user-attachments/assets/299e3dc1-ed6b-4284-8056-9a190c76caae)

**Comment by lunias** [comment]
Thanks for checking! I guess I'll try reinstalling since it sounds like it's an issue w/ my environment.
