### ISSUE TITLE
Explicit Target Mesh Optimization

### ISSUE THREAD

**Issue by clemecleme** [jakechai/ComfyUI-JakeUpgrade#30]
Hi Jack,
Your workflows are awesome, thanks a lot!
Have you ever been confronted to ComfyUI crashing when going through Explicit Target Mesh Optimization process?
I've seen other people having this problem but can't figure out why - tried to update Comfyui, isolate it to get the good Pytorch and xformers version, update matplotlib, etc. 
Any recommandation would be wonderful, thanks!

![ComfyUI_crash](https://github.com/user-attachments/assets/f749725f-9d86-4db4-a4ea-f3ad39a6b77f)
![Eventviewer_error](https://github.com/user-attachments/assets/b7f7282b-a85c-44c4-8087-4c53da611f54)

**Comment by jakechai** [comment]
I have the same problem and I am waiting for the 3D-pack author to provide the corresponding answer.

**Comment by clemecleme** [comment]
Good to know! Thanks for your answer :)
