### ISSUE TITLE
Lora Prompt not being corrected displayed

### ISSUE THREAD

**Issue by imHugoLeandro** [jakechai/ComfyUI-JakeUpgrade#38]
![Screenshot_1894](https://github.com/user-attachments/assets/19e70116-dcac-46a9-aa00-718606232a0c)

Hello, as the image shows, I wanted to save the loras for CivitAI. But the first Lora is always incorrectly saved without "<>". Thank you!

**Comment by jakechai** [comment]
Thanks for the question, but no worries. If the Lora weight equals 1.0, prompt output without <> and still works.
To clarify the misunderstanding, I will cancel this setting.

**Comment by jakechai** [comment]
v1.1.1 fixed.

**Comment by imHugoLeandro** [comment]
![Screenshot_1895](https://github.com/user-attachments/assets/5fe5624c-9490-4b13-b767-e4ee5c67206e)

Thank you so much <3 Fixed!
