### ISSUE TITLE
Not a custom node issue, but question to extract orbit posses

### ISSUE THREAD

**Issue by GeorgeSte** [jakechai/ComfyUI-JakeUpgrade#77]
Hi Jake, I'm working on combining the CRM MV with the reconstruction from Unique 3D, having an issue with the orbit poses, is there a way to extract the orbit poses to text to understand what they are? As I understand I would need to send 4 out of the 6 images from CRM MV to Unique 3D (Fast Normal Maps To Mesh, first in the chain) but running into an error "The view direction is not correct. cos_angles.mean()=0.05275870859622955" though there should be an angle of 0 on the 4 images as they are from the front, side, back and side perspective. Any help would be appreciated

**Comment by jakechai** [comment]
![convert orbit pose](https://github.com/user-attachments/assets/97f8fac1-8d32-49b8-8dde-4806d9d32b08)

In the [JK_workflow_img2mesh_CRM&Zero123plus&MVDream&CharacterGen](https://github.com/jakechai/ComfyUI-JakeUpgrade/blob/master/Workflow/Main/JK_workflow_img2mesh_CRM&Zero123plus&MVDream&CharacterGen.json) workflow, there's the orbit poses conversion process.

![poses](https://github.com/user-attachments/assets/6f1b01b5-ae0c-4225-b4df-6326a31f09f3)

Please also check my video [ComfyUI JakeUpgrade img2mesh Workflow](https://www.youtube.com/watch?v=CbG2Vq3kps0) to learn about the poses.

**Comment by GeorgeSte** [comment]
Thanks Jake! super helpful! :)
